name: Query GitHub Runners

on:
  push:
    branches: [main]

jobs:
  list-runners:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-latest
          - windows-2022
          - macos-latest
          - macos-15
          - macos-14
    steps:
      - name: Display runner OS
        run: |
          echo "Current OS: ${{ matrix.os }}"
